### ISSUE TITLE
can not library the "rEDM"

### ISSUE THREAD

**Issue by tigerwang1998** [SugiharaLab/rEDM#55]
I installed rEDM to Windows. When I  "library(rEDM)", the R program hanged up. After waiting for more than 2 hours, the library ended.Then I can use this package. 
My R version is 4.1.2 and rEDM version is 1.9.3.
Do you have any suggestions/comments about this?
I would be grateful if you could reply to my question.

Thanks!

**Comment by SoftwareLiteracy** [comment]
Please provide the following information from the R console:

```
> sessionInfo()
> La_version()
```

**Comment by tigerwang1998** [comment]
&gt; sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)


Matrix products: default


Random number generation:
&nbsp;RNG:&nbsp; &nbsp; &nbsp;Mersenne-Twister&nbsp;
&nbsp;Normal:&nbsp; Inversion&nbsp;
&nbsp;Sample:&nbsp; Rounding&nbsp;
&nbsp;
locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936&nbsp; LC_CTYPE=Chinese (Simplified)_China.936&nbsp; &nbsp;
[3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
[5] LC_TIME=Chinese (Simplified)_China.936&nbsp; &nbsp;&nbsp;


attached base packages:
[1] stats&nbsp; &nbsp; &nbsp;graphics&nbsp; grDevices utils&nbsp; &nbsp; &nbsp;datasets&nbsp; methods&nbsp; &nbsp;base&nbsp; &nbsp; &nbsp;


other attached packages:
[1] rEDM_1.9.3


loaded via a namespace (and not attached):
[1] compiler_4.1.2 tools_4.1.2&nbsp; &nbsp; Rcpp_1.0.7&nbsp; &nbsp;&nbsp;
&gt; La_version()
[1] "3.9.0"





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SugiharaLab/rEDM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月24日(星期三) 下午2:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SugiharaLab/rEDM] can not library the "rEDM" (Issue #55)





 
Please provide the following information from the R console:
 &gt; sessionInfo() &gt; La_version()  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SoftwareLiteracy** [comment]
This looks like a valid configuration,  Since this is very well tested by CRAN, it suggests there is an issue on the computer where the installation is made.  Issues can arise from multiple installations/versions of R, or, from manually compiling/installing the package.  

Do you have a single, clean installation of R 4.12?

Was rEDM was installed with `install.pacakges('rEDM')` ?

**Comment by tigerwang1998** [comment]
The version of R I used before was 3.6.3. When I encountered this problem, I upgraded R to 4.1.2.

I installed rEDM with  `install.packages('rEDM')`

In addition, I tried to install rEDM on different computers, and this problem occurred

**Comment by SoftwareLiteracy** [comment]
This may come from the upgrade.  It is my understanding that all packages which are compiled (like rEDM) must be rebuilt when a new major version (3 to 4) of R is used.  This might be addressed with `update.packages( checkBuilt = TRUE )`.

When CRAN builds and tests the packages, it is always done on a "clean" installation where R is installed for the first time, then the package.  

You have tried this on a computer that has R 4.12 installed as the first and only installation of R?

**Comment by tigerwang1998** [comment]
I have updated all packages，but rEDM still libraries for 2 hours.

I have tried to install rEDM on R 3.6 first，and the problem occured，so I upgraded R to 4.12. But it doesn't solve the problem.
So I changed several computers to see if there was a problem with my computer. These computers R version are 3.6 、4.05、4.12. The same problem as my computer.

**Comment by SoftwareLiteracy** [comment]
To be clear: when you changed computers to say 4.1.2, this computer never had R installed?

On the computer you updated, you ran `update.packages( checkBuilt = TRUE )` ?

**Comment by tigerwang1998** [comment]
When I changed computers to R 4.1.2, this computer had R installed before.

All the computer I used had R installed with different versions.

The way I updata is  `update.packages( checkBuilt = TRUE )` or update in Rstudio.

So I need unload R entirely and reinstall R？

**Comment by SoftwareLiteracy** [comment]
If you have run `update.packages( checkBuilt = TRUE )`, then I think the only option is to completely remove R and install a clean version of 4.1.2.  This is how CRAN builds and tests packages. 

I have seen reports of other packages where Windows "gets confused" from multiple R installations/upgrades. 

RStudio adds another layer, where incompatible versions of dll's/PATH can exist in Windows.

**Comment by tigerwang1998** [comment]
OK,I will reinstall R to try again.

Thank you very much for your help!

**Comment by tigerwang1998** [comment]
Sadly, I tried to library rEDM on several computers that have never installed R, but the same problem still occurred.

**Comment by SoftwareLiteracy** [comment]
This is with base R, or RStudio?

If it is base R, the issue is likely a local system/configuration issue, since this package is built and tested by CRAN and many other users with no problems.  For example, if the computer has administrative policies that prevent access to certain directories, or, the version of Windows is old. 

I see that your version is : Windows 10 x64 (build 18362); which is Windows version 1903 relased in 2019. 

Current versions are 2004 & above, with builds 19041 and above. Do you have a computer with a version of Windows above 2004?

To check the package installation, you can run `install.packages( 'rEDM', keep_outputs = FALSE )` which will create an output file of the installation process.

**Comment by tigerwang1998** [comment]
I've tried both R and rstudio. 
I have a computer with a version of Windows above 2004,It faild to library as well.
Could you try to test it on Windows?

**Comment by tigerwang1998** [comment]
Amazing，I changed my system language from Chinese to English,then it works.
Thanks for your reply and patience！

**Comment by SoftwareLiteracy** [comment]
Good news! Thank you for feedback!

Please elaborate how you made this change, it sounds like a Windows system setting?  Or was it in base R, or RStudio?

**Comment by tigerwang1998** [comment]
I found this website by accident,[https://github.com/ha0ye/rEDM/issues/19](url)

**Comment by SoftwareLiteracy** [comment]
Thank you! So there is a Chinese language encoding problem that causes package loading to hang/crash. 

Please let us know how you solved it on your machine.  Windows system encoding, or R language encoding?

**Comment by tigerwang1998** [comment]
Windows system encoding I think.
You can change the system language to check it on your pc.

**Comment by tigerwang1998** [comment]
Hope that you can solve this problem as soon as possible, because many software conflicts in English language.Thank you again for your efforts！

**Comment by SoftwareLiteracy** [comment]
Thank you for your feedback identifying and finding a work around for this problem. 

Unfortunately, at the moment, this is a single-peson volunteer effort on my behalf.  So this is relegated to non-work hours. Also, I do not work on WIndows, and, it is not feasible for me to test in Chinese.  

If you are willing to help with testing, we can look for a more definitive answer.   If so. please email me directly JosephPark@SoftwareLiteracyFoundation,org, and we can continue with diagnosis. 

The issue seems to be that there are encodings in the package that cause Windows version of R to hang when the Windows system uses Chinese encoding.  Perhaps the documentation or vignettes have characters that are not being handled properly in the loading of the library.

**Comment by SoftwareLiteracy** [comment]
Just want to mention that if you are not tied to R, or need the additional functionality (s-map regularization...), the Python interface wraps the same computation engine as rEDM: [https://pypi.org/project/pyEDM/](https://pypi.org/project/pyEDM/)

Since Python packages don't embedd all the stuff that R packages do, perhaps that is another work around.

**Comment by tigerwang1998** [comment]
OK,I will try to learn it.Thank you so much!
