### ISSUE TITLE
GPU acceleration?  (feature)

### ISSUE THREAD

**Issue by kamal94** [SugiharaLab/rEDM#8]
I used CCM in a massive and resource consuming research project, and some of my simulations took days to complete even with using a small number of random samples. Which made me think of possible acceleration methods that we can implement for CCM, especially with iterative computations on the same data.

I think CCM is a great tool, and should not be hindered by the computational complexity that neural networks and other algorithms have been able to surpass with computational optimization.

Since some if not most of the work done by CCM is calculating distances, would this not be a local operation that can be distributed to many nodes? Perhaps after a "master" manifold has been built?

Any ideas? I would be happy to help with what I can.

**Comment by ha0ye** [comment]
Distributed computing is one solution. A development version of rEDM used C++11 threading, but I commented out the code because Rtools at the time did not support that feature. I haven't checked since to see if that situation has changed. There are probably ways of using a distributed network for computation, but I'm not familiar with the technology for doing so, and it's outside the scope of my research at the moment.

Another option is algorithmic improvements. We currently do the naive "calculate all distances and find the nearest neighbors" method, but k-d trees are a standard alternative (at least for low dimensionality, I think?). In higher dimensions, it's less effective (one of the corollaries to curse of dimensionality), but I would guess different distance metrics might be preferred, and then you'd want a custom algo. anyway.

Regardless, I encourage you to fork the package and have a go if you like (esp. if you just want to play around with the C++11 multi-threading code).
